### ISSUE TITLE
Pelican Admin is looking to access django db util to check for database error?

### ISSUE THREAD

**Issue by seawolff** [fjcaetano/pelican_admin#1]
Not sure why this package would be looking to access my db on installation of the package.

```
Running setup.py (path:/home/vagrant/.virtualenvs/doc-app/build/pelican-admin/setup.py) egg_info for package pelican-admin
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vagrant/.virtualenvs/doc-app/build/pelican-admin/setup.py", line 5, in <module>
        import pelican_admin
      File "pelican_admin/__init__.py", line 69, in <module>
        except django.db.utils.DatabaseError, e:
    AttributeError: 'module' object has no attribute 'db'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/vagrant/.virtualenvs/doc-app/build/pelican-admin/setup.py", line 5, in <module>

    import pelican_admin

  File "pelican_admin/__init__.py", line 69, in <module>

    except django.db.utils.DatabaseError, e:

AttributeError: 'module' object has no attribute 'db'
```

**Comment by fjcaetano** [comment]
Configs, posts, etc, are backed up in the DB for more easily editing. The README.md explicitly advises you to syncdb or migrate with south.

However, this project was discontinued. You can see the last development commit was over an year ago, so I should advise you against using this for other than educational purposes.

**Comment by seawolff** [comment]
I did notice this. I just wanted to point out that is a rather strange practice for a package install.
